server {
    listen 80;
    listen [::]:80;

    server_name app.SERVER_IP.sslip.io;
    root /var/www/aastu-jobportal/frontend/dist;

    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
